#开发环境 配置文件
server:
  port: 8093
  maxPostSize: 20971520

#tomcatJdbc 配置信息
spring:
  datasource:
    url: jdbc:mysql://192.168.0.92:3306/aftersale_repairing_platform?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: dev_app
    password: dev123456


#jedis配置
redis:
  database: 0
  host:  192.168.0.78
  port: 6379
  password: zhtdev$123456

  #集群配置
  cluster:
    #多个节点以逗号分隔
    clusterNodes: 192.168.0.78:6379,192.168.0.78:6380,192.168.0.78:6381,192.168.0.78:6382,192.168.0.78:6383,192.168.0.78:6384
    password: zhtdev$123456

  perfix:
    projectcode: servicedev:projectcode


#单点登录相关配置
oauth:
  center:
    #认证中心路径
    url: http://192.168.0.48:8081


#本系统相关配置
base:
  #本系统域名
  url: http://localhost:15201
  #本系统的appid
  appid: c873890d60ad4e8c92705d4872ccac90
  #本系统的secret
  secret: 883c12f76921465aa5bfb74e9d9ac9cc
  #顶级服务中心code
  topservicecenter: "SC000002"
  #客户经理组织机构
  custmanager: "SC000003"
  #客户经理角色code
  custmanagerrolecode: "JS024"

#web端配置:
cookie:
  #cookie的domain,设置访问域
  #domain: ccbuluo.cn

#验证码配置
verification:
  #本系统是否开启后端验证码校验,有值且为true时,有效
  check: false


#dev开发环境中配置默认登录用户:
dev-default:
  #是否开启自动登录 只要有值即可!
  #needLogin: need
  username: "ZHT00512"
  password: "ZHT00512"



#swagger相关配置
swagger:
  basePackage: com.ccbuluo
  title: 售后服务平台PC端接口
  version: 1.0.0
  description: 售后服务平台PC端api

#文件上传目录
oss:
  bucket-name: zht-dev-nosec

#thrift微服务配置
ccbuluo:
  thrift:
    service:
      basePackages: com
    zookeeper:
      server: 192.168.0.78:2181

